model:
  name: 'osnet_ain_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'color_jitter']
  save_dir: 'log/theirs_duke2duke'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 150
  batch_size: 32
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False